name: eddistudy
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eddistudy
    volumes:
      - dbdata:/var/lib/postgresql/data

  obj:
    image: minio/minio
    restart: always
    ports:
      - 9001:9000
      - 9090:9090
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - objdata:/data
    command: server /data --console-address ":9090"

  obj_buckets:
    image: minio/mc
    depends_on:
      - obj
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://obj:9000 minio minio123;
      /usr/bin/mc mb myminio/schools;
      /usr/bin/mc mb myminio/logos;
      /usr/bin/mc anonymous set public myminio/logos;
      exit 0;
      "
  chromadb:
    image: chromadb/chroma:latest
    container_name: eddistudy-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
      - ALLOW_RESET=TRUE
    networks:
      - eddistudy-network

networks:
  eddistudy-network:
    driver: bridge
    
volumes:
  dbdata:
  objdata:
